# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6064b5bc97f786e80cb0734f09cdd1b1dd3c2aeb032c5aae95a8ff3c167d92a823a71fb4125a51bca661008b036aef1eb4c79f462acd315ca6ac0982e01aa3ca

test:
  secret_key_base: 5f655d4d864c9dca419955e3b80b4b08b03e1e536cb29940e7df674e43cb5f95ae4ee1a3fd7e9d9ac30d66d851348638bbd7f47ce6a448a43a021dbe07cd788c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
